name: iverilog
on: [pull_request]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: sudo apt-get install iverilog
    - name: Run iVerilog
      run: ./run_unit_tests.sh
  fib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: sudo apt-get install iverilog
    - name: Run iVerilog
      run: ./run_fib.sh
