name: iverilog
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: sudo apt-get install iverilog
    - name: Run iVerilog
      run: ./run.sh
